/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.HoSo;
import model.TbHoSo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.DBEngine;
import model.TaiKhoan;

/**
 *
 * @author Phạm Trí Đức
 */
public class QLHoSoSinhVien extends javax.swing.JFrame {
    DBEngine db = new DBEngine();
    ArrayList<HoSo> dshs=new ArrayList<>();
        HoSo hs = new HoSo();
        int dongChon = -1;

    /**
     * Creates new form QLHoSoSinhVien
     */
    public QLHoSoSinhVien() {
        initComponents();
        fakeData();
        loadTable(dshs);
    }
    public void fakeData(){
        HoSo hs1=new HoSo("1","Pham tri duc","nam","11/7/2002","Vinh Phuc","KTPM1","K15","KTPM","phamtriduc@gmail.com","ko","ko","0334451293","90","Cau Long");
        dshs.add(hs1);
        HoSo hs2=new HoSo("1","Pham tri duc","nam","11/7/2002","Vinh Phuc","KTPM1","K15","KTPM","phamtriduc@gmail.com","ko","ko","0334451293","90","Cau Long");
        dshs.add(hs2);
        HoSo hs3=new HoSo("1","Pham tri duc","nam","11/7/2002","Vinh Phuc","KTPM1","K15","KTPM","phamtriduc@gmail.com","ko","ko","0334451293","90","Cau Long");
        dshs.add(hs3);
        
    }
    public void loadTable(ArrayList<HoSo> dshs ){
        TbHoSo.setModel(new TbHoSo(dshs));
    }
     public void Clear(){
        TxtLop.setText("");
        txtBaoLuu.setText("");
        txtDiaChi.setText("");
        txtDiemRenLuyen.setText("");
        txtEmail.setText("");
        txtGhiChu.setText("");
        txtGioiTinh.setText("");
        txtkhoa.setText("");
        txtMaSinhVien.setText("");
        txtSothich.setText("");
        txtnganh.setText("");
        txtNgaySinh.setText("");
        txtSDT.setText("");
        txtTenSinhVien.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtLop = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtNganh = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtKhoa = new javax.swing.JTextPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnThem = new javax.swing.JButton();
        BtnSua = new javax.swing.JButton();
        BtnXoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtNgaySinh = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMaSinhVien = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        TbHoSo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTenSinhVien = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtnganh = new javax.swing.JTextPane();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtkhoa = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        TxtLop = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        txtDiemRenLuyen = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        txtBaoLuu = new javax.swing.JTextPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        txtSothich = new javax.swing.JTextPane();
        jScrollPane22 = new javax.swing.JScrollPane();
        txtEmail = new javax.swing.JTextPane();
        jScrollPane23 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextPane();
        jScrollPane24 = new javax.swing.JScrollPane();
        txtSDT = new javax.swing.JTextPane();
        jScrollPane25 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextPane();
        BtnXOA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGioiTinh = new javax.swing.JTextPane();
        BtnQuayLai = new javax.swing.JButton();
        btnDocFile = new javax.swing.JButton();
        btnGhiFile = new javax.swing.JButton();

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Điểm rèn luyện");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Khóa");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ngành");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lớp");

        txtLop.setEditable(false);
        jScrollPane12.setViewportView(txtLop);

        txtNganh.setEditable(false);
        jScrollPane13.setViewportView(txtNganh);

        txtKhoa.setEditable(false);
        jScrollPane4.setViewportView(txtKhoa);

        jScrollPane19.setViewportView(jTextPane7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lý hồ sơ sinh viên");

        BtnThem.setBackground(new java.awt.Color(51, 153, 255));
        BtnThem.setForeground(new java.awt.Color(255, 255, 255));
        BtnThem.setText("Thêm");
        BtnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnThemMouseClicked(evt);
            }
        });
        BtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemActionPerformed(evt);
            }
        });

        BtnSua.setBackground(new java.awt.Color(51, 153, 255));
        BtnSua.setForeground(new java.awt.Color(255, 255, 255));
        BtnSua.setText("Sửa");
        BtnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSuaMouseClicked(evt);
            }
        });

        BtnXoa.setText("Xóa");
        BtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXoaActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên sinh viên");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mã sinh viên");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ngày sinh");

        jScrollPane11.setViewportView(txtNgaySinh);

        jScrollPane3.setViewportView(txtMaSinhVien);

        TbHoSo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TbHoSo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbHoSoMouseClicked(evt);
            }
        });
        jScrollPane16.setViewportView(TbHoSo);

        jScrollPane2.setViewportView(txtTenSinhVien);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Khóa");

        jScrollPane5.setViewportView(txtnganh);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ngành");

        jScrollPane8.setViewportView(txtkhoa);

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Giới tính");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Lớp");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Điểm rèn luyện");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Bảo lưu");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Sở thích");

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Email");

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("SĐT");

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Ghi chú");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Địa chỉ");

        jScrollPane17.setViewportView(TxtLop);

        jScrollPane18.setViewportView(txtDiemRenLuyen);

        jScrollPane20.setViewportView(txtBaoLuu);

        jScrollPane21.setViewportView(txtSothich);

        jScrollPane22.setViewportView(txtEmail);

        jScrollPane23.setViewportView(txtDiaChi);

        jScrollPane24.setViewportView(txtSDT);

        jScrollPane25.setViewportView(txtGhiChu);

        BtnXOA.setBackground(new java.awt.Color(51, 153, 255));
        BtnXOA.setForeground(new java.awt.Color(255, 255, 255));
        BtnXOA.setText("Xóa");
        BtnXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXOAActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtGioiTinh);

        BtnQuayLai.setBackground(new java.awt.Color(51, 153, 255));
        BtnQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        BtnQuayLai.setText("Quay lại");
        BtnQuayLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnQuayLaiMouseClicked(evt);
            }
        });
        BtnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuayLaiActionPerformed(evt);
            }
        });

        btnDocFile.setBackground(new java.awt.Color(51, 153, 255));
        btnDocFile.setForeground(new java.awt.Color(255, 255, 255));
        btnDocFile.setText("Đọc file");
        btnDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocFileActionPerformed(evt);
            }
        });

        btnGhiFile.setBackground(new java.awt.Color(51, 153, 255));
        btnGhiFile.setForeground(new java.awt.Color(255, 255, 255));
        btnGhiFile.setText("Ghi file");
        btnGhiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3393, 3393, 3393)
                        .addComponent(BtnXoa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 1475, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(BtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(BtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(BtnXOA, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(BtnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(btnDocFile)
                        .addGap(147, 147, 147)
                        .addComponent(btnGhiFile))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(jScrollPane3)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel21)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jScrollPane17)
                            .addComponent(jScrollPane20)
                            .addComponent(jScrollPane21)
                            .addComponent(jScrollPane1))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane22, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(jScrollPane23)
                            .addComponent(jScrollPane24)
                            .addComponent(jScrollPane25))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel24)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel4)
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel14))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addComponent(jLabel22))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel27)))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel25)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel21)
                                                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnXOA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGhiFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(BtnXoa)
                .addGap(98, 98, 98))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void BtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnXoaActionPerformed

    private void BtnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSuaMouseClicked
        dongChon = TbHoSo.getSelectedRow();
        try {
            if(dongChon != -1){
                hs = dshs.get(dongChon);
                hs.setEmail(getTxtEmail());
                hs.setHoten(getTxtHoTen());
                hs.setDiemrenluyen(getTxtDiemRenLuyen());
                hs.setNgaysinh(getTxtNgaySinh());
                hs.setGhichu(getTxtGhiChu());
                hs.setLop(getTxtLop());
                hs.setKhoa(getTxtKhoa());
                hs.setMaSV(getTxtMaSV());
                hs.setNganh(getTxtNganh());
                hs.setSothich(getTxtSoThich());
                hs.setGioitinh(getTxtGioiTinh());
                hs.setDiachi(getTxtDiaChi());
                hs.setBaoluu(getTxtBaoLuu());
                
                Clear();
                JOptionPane.showConfirmDialog(this,"Sửa thành công","Thông báo",JOptionPane.CLOSED_OPTION);
                loadTable(dshs);
            }else{
                throw new Exception("Vui lòng chọn dòng");
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e.toString(),"Thông báo",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BtnSuaMouseClicked

    private void BtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnThemActionPerformed

    private void BtnXOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXOAActionPerformed
        dongChon = TbHoSo.getSelectedRow();
        try {
            if(dongChon != -1){
                int confirm = JOptionPane.showConfirmDialog(this,"Bạn chắc chắc muốn xoá ?","Xác nhận",JOptionPane.YES_NO_OPTION);
                if(confirm == JOptionPane.YES_OPTION){
                    hs = dshs.get(dongChon);
                    dshs.remove(dongChon);
                    Clear();
                    loadTable(dshs);
                }
            }else{
                throw new Exception("Vui lòng chọn dòng");
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e.toString(),"Thông báo",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BtnXOAActionPerformed
    public String getTxtSoThich(){
        return txtSothich.getText().trim();
    }
    public String getTxtEmail(){
        return txtEmail.getText().trim();
    }
    
    public String gettxtSDT(){
        return txtSDT.getText().trim();
    }
    public String getTxtHoTen () throws Exception{
        if(txtTenSinhVien.getText().trim().equals(""))
            throw new Exception("Tên sinh viên không được để trống");
        return txtTenSinhVien.getText().trim();
    }
    public String getTxtMaSV() throws Exception{
        if(txtMaSinhVien.getText().trim().equals(""))
            throw new Exception("Mã sinh viên không được để trống");
        return txtMaSinhVien.getText().trim();
    }
    public String getTxtGioiTinh()throws Exception{
        if(txtGioiTinh.getText().trim().equals(""))
            throw new Exception("Giới tính không được để trống");
        return txtGioiTinh.getText().trim();
    }
    public String getTxtNgaySinh()throws Exception{
        if(txtNgaySinh.getText().trim().equals(""))
            throw new Exception("Ngày sinh không được để trống");
        return txtNgaySinh.getText().trim();
    }
    public String getTxtLop()throws Exception{
        if(txtLop.getText().trim().equals(""))
            throw new Exception("Lớp không được để trống");
        return TxtLop.getText().trim();
    }
    public String getTxtDiemRenLuyen()throws Exception{
        return txtDiemRenLuyen.getText().trim();
    }
    public String getTxtGhiChu()throws Exception{
        return txtGhiChu.getText().trim();
    }
    public String getTxtKhoa()throws Exception{
        if(txtKhoa.getText().trim().equals(""))
            throw new Exception("Khoa không được để trống");
        return txtkhoa.getText().trim();
    }
    public String getTxtNganh()throws Exception{
        if(txtnganh.getText().trim().equals(""))
            throw new Exception("Ngành không được để trống");
        return txtnganh.getText().trim();
    }
    public String getTxtDiaChi()throws Exception{
        return txtDiaChi.getText().trim();
    }
    public String getTxtBaoLuu()throws Exception{
        return txtBaoLuu.getText().trim();
    }
    private void TbHoSoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbHoSoMouseClicked
       dongChon = TbHoSo.getSelectedRow();
        if(dongChon != -1){
            hs = dshs.get(dongChon);
        
          
        txtDiemRenLuyen.setText(hs.getDiemrenluyen());
        txtBaoLuu.setText(hs.getBaoluu());
        txtEmail.setText(hs.getEmail());
        txtGhiChu.setText(hs.getGhichu());
        TxtLop.setText(hs.getLop());
        txtkhoa.setText(hs.getKhoa());
        txtMaSinhVien.setText(hs.getMaSV());
        txtnganh.setText(hs.getNganh());
        txtSothich.setText(hs.getSothich());
        txtGioiTinh.setText(hs.getGioitinh());
        txtDiaChi.setText(hs.getDiachi());
        txtTenSinhVien.setText(hs.getHoten());
        txtNgaySinh.setText(hs.getNgaysinh());
        txtSDT.setText(hs.getSdt());
        }
    }//GEN-LAST:event_TbHoSoMouseClicked

    private void BtnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnThemMouseClicked
        try {
            int dem = 0;
            HoSo tk = new HoSo();
            hs.setEmail(getTxtEmail());
                hs.setHoten(getTxtHoTen());
                hs.setDiemrenluyen(getTxtDiemRenLuyen());
                hs.setNgaysinh(getTxtNgaySinh());
                hs.setGhichu(getTxtGhiChu());
                hs.setLop(getTxtLop());
                hs.setKhoa(getTxtKhoa());
                hs.setMaSV(getTxtMaSV());
                hs.setNganh(getTxtNganh());
                hs.setSothich(getTxtSoThich());
                hs.setGioitinh(getTxtGioiTinh());
                hs.setDiachi(getTxtDiaChi());
                hs.setBaoluu(getTxtBaoLuu());
            for(HoSo i:dshs){
                if(hs.getHoten().equals(i.getHoten()) || tk.getMaSV().equals(i.getMaSV())){
                    dem++;
                }
            }
            if(dem==0){
                Clear();
                dshs.add(tk);
                loadTable(dshs);
            }else{
                throw new Exception("Hồ sơ sinh viên đã tồn tại");
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e.toString(),"Thông báo",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_BtnThemMouseClicked

    private void BtnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQuayLaiActionPerformed
        // TODO add your handling code here:
        MenuAdmin m = new MenuAdmin();
        m.show();
        this.hide();
    }//GEN-LAST:event_BtnQuayLaiActionPerformed

    private void BtnQuayLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnQuayLaiMouseClicked

    }//GEN-LAST:event_BtnQuayLaiMouseClicked

    private void btnDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocFileActionPerformed
        // TODO add your handling code here:
        dshs = new ArrayList<>();
        try {
            dshs = (ArrayList<HoSo>) db.docFile("HoSo.txt");
            JOptionPane.showConfirmDialog(this,"Đọc file thành công","Thông báo",JOptionPane.CLOSED_OPTION);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e.toString(),"Thông báo",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_btnDocFileActionPerformed

    private void btnGhiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiFileActionPerformed
        // TODO add your handling code here:
        try {
            db.luuFile("HoSo.txt", dshs);
            JOptionPane.showConfirmDialog(this,"Ghi file thành công","Thông báo",JOptionPane.CLOSED_OPTION);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e.toString(),"Thông báo",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGhiFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLHoSoSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLHoSoSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLHoSoSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLHoSoSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QLHoSoSinhVien().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnQuayLai;
    private javax.swing.JButton BtnSua;
    private javax.swing.JButton BtnThem;
    private javax.swing.JButton BtnXOA;
    private javax.swing.JButton BtnXoa;
    private javax.swing.JTable TbHoSo;
    private javax.swing.JTextPane TxtLop;
    private javax.swing.JButton btnDocFile;
    private javax.swing.JButton btnGhiFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane txtBaoLuu;
    private javax.swing.JTextPane txtDiaChi;
    private javax.swing.JTextPane txtDiemRenLuyen;
    private javax.swing.JTextPane txtEmail;
    private javax.swing.JTextPane txtGhiChu;
    private javax.swing.JTextPane txtGioiTinh;
    private javax.swing.JTextPane txtKhoa;
    private javax.swing.JTextPane txtLop;
    private javax.swing.JTextPane txtMaSinhVien;
    private javax.swing.JTextPane txtNganh;
    private javax.swing.JTextPane txtNgaySinh;
    private javax.swing.JTextPane txtSDT;
    private javax.swing.JTextPane txtSothich;
    private javax.swing.JTextPane txtTenSinhVien;
    private javax.swing.JTextPane txtkhoa;
    private javax.swing.JTextPane txtnganh;
    // End of variables declaration//GEN-END:variables
}
