package ui;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.DBEngine;
import model.LichThi;
import model.TableLichThi;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public final class QuanLyLichThiDemo extends javax.swing.JFrame {

    int dongChon = -1;
    ArrayList<LichThi> dslt = new ArrayList<>();
    DBEngine db = new DBEngine();
    LichThi lt = new LichThi();
    /**
     * Creates new form QuanLyLichThiDemo
     */
    public QuanLyLichThiDemo() {
        initComponents();
        fakeData();
        loadTable(dslt);
    }
    
      public void fakeData(){
        LichThi lt1 = new LichThi(1, "Java", "2/6/2023", "13h00", 135798,"B2","701A1",1);
        dslt.add(lt1);
        LichThi lt2 = new LichThi(2, "Java", "2/6/2023", "13h00", 135798,"B2","701A1",1);
        dslt.add(lt2);
        LichThi lt3 = new LichThi(3, "Java", "2/6/2023", "13h00", 135798,"B2","701A1",1);
        dslt.add(lt3);
        LichThi lt4 = new LichThi(4, "Java", "2/6/2023", "13h00", 135798,"B2","701A1",1);
        dslt.add(lt4);   
    }
    public void loadTable(ArrayList<LichThi> dslt ){
        tbXemLichThi.setModel(new TableLichThi(dslt));
    }
    public void Clear(){
        txtSTT.setText("");
        txtMonThi.setText("");
        txtNgayThi.setText("");
        txtCaThi.setText("");
        txtSBD.setText("");
        txtViTri.setText(""); 
        txtPhongThi.setText("");
        txtLanThi.setText("");      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfCaThi = new javax.swing.JTextField();
        tfSBD = new javax.swing.JTextField();
        tfVitri = new javax.swing.JTextField();
        tfPhongThi = new javax.swing.JTextField();
        tfLanthi = new javax.swing.JTextField();
        tfSTT = new javax.swing.JTextField();
        tfMonThi = new javax.swing.JTextField();
        tfNgayThi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbXemLichThi = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnQuayLai = new javax.swing.JButton();
        txtSTT = new javax.swing.JTextField();
        txtMonThi = new javax.swing.JTextField();
        txtNgayThi = new javax.swing.JTextField();
        txtCaThi = new javax.swing.JTextField();
        txtSBD = new javax.swing.JTextField();
        txtViTri = new javax.swing.JTextField();
        txtPhongThi = new javax.swing.JTextField();
        txtLanThi = new javax.swing.JTextField();
        btnDocfide = new javax.swing.JButton();
        btnGhifide = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfCaThi.setText("Ca thi");
        tfCaThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCaThiActionPerformed(evt);
            }
        });

        tfSBD.setText("SBD");

        tfVitri.setText("Vị trí");
        tfVitri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVitriActionPerformed(evt);
            }
        });

        tfPhongThi.setText("Phòng thi");

        tfLanthi.setText("Lần thi:");

        tfSTT.setText("STT");
        tfSTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSTTActionPerformed(evt);
            }
        });

        tfMonThi.setText("Môn thi");

        tfNgayThi.setText("Ngày thi");
        tfNgayThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNgayThiActionPerformed(evt);
            }
        });

        tbXemLichThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbXemLichThi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbXemLichThiAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbXemLichThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbXemLichThiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbXemLichThi);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Thông tin lịch thi");

        btnQuayLai.setText("< Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        txtCaThi.setToolTipText("");

        txtSBD.setText(" ");

        txtViTri.setText(" ");

        txtPhongThi.setText(" ");

        txtLanThi.setText(" ");

        btnDocfide.setText("Đọc file");
        btnDocfide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocfideActionPerformed(evt);
            }
        });

        btnGhifide.setText("Ghi file");
        btnGhifide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhifideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuayLai)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(46, 46, 46)
                                .addComponent(btnSua)
                                .addGap(48, 48, 48)
                                .addComponent(btnXoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDocfide)
                                .addGap(39, 39, 39)
                                .addComponent(btnGhifide))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfMonThi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtMonThi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfNgayThi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtNgayThi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfCaThi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtCaThi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfSTT, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtSTT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfPhongThi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfVitri, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfSBD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfLanthi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(70, 70, 70)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPhongThi)
                                    .addComponent(txtLanThi, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(txtViTri)
                                    .addComponent(txtSBD))))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnQuayLai)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMonThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVitri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNgayThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPhongThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhongThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCaThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLanthi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLanThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnThem)
                    .addComponent(btnDocfide)
                    .addComponent(btnGhifide))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCaThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCaThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCaThiActionPerformed

    private void tfVitriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVitriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVitriActionPerformed

    private void tfSTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSTTActionPerformed

    private void tfNgayThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNgayThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNgayThiActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        QuanLyLichThi qllt = new QuanLyLichThi();
        qllt.show();
        this.hide();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
       try {
            int dem = 0;
            LichThi lt = new LichThi();
            lt.setSTT(Integer.parseInt(getTxtSTT()));
            lt.setMonThi(getTxtMonThi());
            lt.setNgayThi(getTxtNgayThi());
            lt.setCaThi(getTxtCaThi());
            lt.setSBD(Integer.parseInt(getTxtSBD()));
            lt.setViTri(getTxtViTri());
            lt.setPhongThi(getTxtPhongThi());
            lt.setLanThi(Integer.parseInt(getTxtLanThi()));
            for(LichThi i:dslt){
                if(lt.getMonThi().equals(i.getMonThi())){
                    dem++;
                }
            }
            if(dem==0){
                Clear();
                dslt.add(lt);
                loadTable(dslt);
            }else{
                throw new Exception("Môn thi đã tồn tại");
            }
            
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(this, ex.toString(),"Thông báo",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
          dongChon = tbXemLichThi.getSelectedRow();
        try {
            if(dongChon != -1){
                lt = dslt.get(dongChon);
                lt.setMonThi(getTxtMonThi());
                lt.setNgayThi(getTxtMonThi());
                lt.setCaThi(getTxtCaThi());
                Clear();
                JOptionPane.showConfirmDialog(this,"Sửa thành công","Thông báo",JOptionPane.CLOSED_OPTION);
                loadTable(dslt);
            }else{
                throw new Exception("Vui lòng chọn dòng");
            }
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(this, ex.toString(),"Thông báo",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        dongChon = tbXemLichThi.getSelectedRow();
        try {
            if(dongChon != -1){
                int confirm = JOptionPane.showConfirmDialog(this,"Bạn chắc chắc muốn xoá ?","Xác nhận",JOptionPane.YES_NO_OPTION);
                if(confirm == JOptionPane.YES_OPTION){
                    lt = dslt.get(dongChon);
                    dslt.remove(dongChon);
                    Clear();
                    loadTable(dslt);
                }
            }else{
                throw new Exception("Vui lòng chọn dòng");
            }
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(this, ex.toString(),"Thông báo",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnGhifideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhifideActionPerformed
        // TODO add your handling code here:
        dslt = new ArrayList<>();
        try {
            dslt = (ArrayList<LichThi>) db.docFile("LichThi.txt");
            JOptionPane.showConfirmDialog(this,"Đọc file thành công","Thông báo",JOptionPane.CLOSED_OPTION);
        } catch (Exception e) {
            System.out.println("Có lỗi: " + e.toString());
        } 
        loadTable(dslt);
    }//GEN-LAST:event_btnGhifideActionPerformed

    private void btnDocfideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocfideActionPerformed
        // TODO add your handling code here:
        try {
            db.luuFile("LichThi.txt", dslt);
            JOptionPane.showConfirmDialog(this,"Ghi file thành công","Thông báo",JOptionPane.CLOSED_OPTION);
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnDocfideActionPerformed

    private void tbXemLichThiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbXemLichThiAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbXemLichThiAncestorAdded

    private void tbXemLichThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbXemLichThiMouseClicked
        // TODO add your handling code here:
         dongChon = tbXemLichThi.getSelectedRow();
        if(dongChon != -1){
            lt = dslt.get(dongChon);
            System.out.println(lt);
            txtSTT.setText(String.valueOf(lt.getSTT()));
            txtMonThi.setText(lt.getMonThi());
            txtNgayThi.setText(lt.getNgayThi());
            txtCaThi.setText(lt.getCaThi());
            txtSBD.setText(String.valueOf(lt.getSBD()));
            txtViTri.setText(lt.getViTri()); 
            txtPhongThi.setText(lt.getPhongThi());
            txtLanThi.setText(String.valueOf(lt.getLanThi()));    
        }
    }//GEN-LAST:event_tbXemLichThiMouseClicked

    /**
     * @param dslt
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyLichThiDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyLichThiDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyLichThiDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyLichThiDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyLichThiDemo().setVisible(true);
            }
        });
    }
    public String getTxtSTT()throws Exception{
        if(txtSTT.getText().trim().equals(""))
            throw new Exception("STT không được để trống");
        return txtSTT.getText().trim();
    }
    public String getTxtPhongThi()throws Exception{
        if(txtPhongThi.getText().trim().equals(""))
            throw new Exception("Phòng thi không được để trống");
        return txtPhongThi.getText().trim();
    }
    public String getTxtLanThi()throws Exception{
        if(txtPhongThi.getText().trim().equals(""))
            throw new Exception("Lần thi không được để trống");
        return txtPhongThi.getText().trim();
    }
    public String getTxtMonThi()throws Exception{
        if(txtMonThi.getText().trim().equals(""))
            throw new Exception("Môn thi không được để trống");
        return txtMonThi.getText().trim();
    }
    public String getTxtNgayThi()throws Exception{
        if(txtNgayThi.getText().trim().equals(""))
            throw new Exception("Ngày thi không được để trống");
        return txtNgayThi.getText().trim();
    }
    public String getTxtCaThi()throws Exception{
        if(txtCaThi.getText().trim().equals(""))
            throw new Exception("Ca thi không được để trống");
        return txtCaThi.getText().trim();
    }
    public String getTxtSBD()throws Exception{
        if(txtSBD.getText().trim().equals(""))
            throw new Exception("Số báo danh không được để trống");
        return txtSBD.getText().trim();
    }
    public String getTxtViTri()throws Exception{
        if(txtViTri.getText().trim().equals(""))
            throw new Exception("Vị trí không được để trống");
        return txtViTri.getText().trim();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocfide;
    private javax.swing.JButton btnGhifide;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbXemLichThi;
    private javax.swing.JTextField tfCaThi;
    private javax.swing.JTextField tfLanthi;
    private javax.swing.JTextField tfMonThi;
    private javax.swing.JTextField tfNgayThi;
    private javax.swing.JTextField tfPhongThi;
    private javax.swing.JTextField tfSBD;
    private javax.swing.JTextField tfSTT;
    private javax.swing.JTextField tfVitri;
    private javax.swing.JTextField txtCaThi;
    private javax.swing.JTextField txtLanThi;
    private javax.swing.JTextField txtMonThi;
    private javax.swing.JTextField txtNgayThi;
    private javax.swing.JTextField txtPhongThi;
    private javax.swing.JTextField txtSBD;
    private javax.swing.JTextField txtSTT;
    private javax.swing.JTextField txtViTri;
    // End of variables declaration//GEN-END:variables


}
